version: "3.7"

networks:
  tpec-be-network:
    driver: bridge

volumes:
  tpec-be-uploads:
    driver: local

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: tpec-be
    container_name: tpec-be
    environment:
      DATABASE_NAME: tpec-be
      DATABASE_HOST: 192.168.22.140
      DATABASE_PORT: 3306
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi

    restart: unless-stopped
    volumes:
      - tpec-be-uploads:/usr/src/app/public/uploads
    ports:
      - 1370:1337
    networks:
      - tpec-be-network
